import sys
import subprocess
from os import listdir

def changeConfig(StrategyNumber,Datafreq,Date,DataType,MATCHINGBAR,MAXINPUTDATALENGTHFORINDICATORS,EXECUTIONTIME,MAXINDICATORPASTVALUES,SLTRADE,SLSYMBOL,SLTOTAL,TRAILINGSL,BOOKPROFIT,ORDERVALUE,GAPBETWEENORDERS,MAXPYRAMIDSIZE,CHECKSIGNALWHENSLORDERISPENDING,INTERDAYSON,VOLUMEBASEDMACTHING,PERCENTAGEVOLUMEMATCHING,ORDERMATCHINGINMULTBARS):
	print ("\nRunning for Date: " + Date)

	configFilePath = "/config.txt"
	stratConfigFilePath =  "/strategyConfig.txt"
        print (configFilePath)
	MATCHINGRULE=1
	SLIPPAGE=0
#	SYMBOL="NIFTY_F1,BANKNIFTY_F1"
#	SYMBOL="NIFTY_F1,BANKNIFTY_F1,LT_F1,ASIANPAINT_F1,HINDALCO_F1,GRASIM_F1,UPL_F1,ULTRACEMCO_F1,SBIN_F1,IOC_F1,ADANIPORTS_F1,SBILIFE_F1,JSWSTEEL_F1,BAJFINANCE_F1,CIPLA_F1,TATASTEEL_F1,HCLTECH_F1,DRREDDY_F1,TECHM_F1,NTPC_F1,INFY_F1,COALINDIA_F1,NESTLEIND_F1,SHREECEM_F1,TCS_F1,HDFCLIFE_F1,HINDUNILVR_F1,WIPRO_F1,BAJAJFINSV_F1,BPCL_F1,HDFC_F1,TATAMOTORS_F1,ONGC_F1,RELIANCE_F1,MARUTI_F1,POWERGRID_F1,AXISBANK_F1,TATACONSUM_F1,EICHERMOT_F1,M&M_F1,BAJAJ-AUTO_F1,DIVISLAB_F1,ITC_F1,TITAN_F1,HEROMOTOCO_F1,BRITANNIA_F1,HDFCBANK_F1,KOTAKBANK_F1,ICICIBANK_F1,BHARTIARTL_F1,INDUSINDBK_F1,SUNPHARMA_F1"
#        SYMBOL="TATASTEEL_F1,BHARTIARTL_F1,JUBLFOOD_F1,VEDL_F1,TCS_F1,HDFCBANK_F1,AXISBANK_F1,EICHERMOT_F1,TATAMTRDVR_F1,CIPLA_F1,NIFTY_F1,DRREDDY_F1,ADANIENT_F1,M&M_F1,UPL_F1,LT_F1,HDFC_F1,PNB_F1,NMDC_F1,BHARATFORG_F1,AMBUJACEM_F1,APOLLOTYRE_F1,LUPIN_F1,ASHOKLEY_F1,LICHSGFIN_F1,BANKNIFTY_F1,UNIONBANK_F1,HINDUNILVR_F1,FEDERALBNK_F1,ASIANPAINT_F1,SBIN_F1,KOTAKBANK_F1,BRITANNIA_F1,NTPC_F1,TATASTEEL_F1,ULTRACEMCO_F1,ZEEL_F1,BAJAJ-AUTO_F1"

        # NIFTY50
#	SYMBOL="LT_F1,ASIANPAINT_F1,HINDALCO_F1,GRASIM_F1,UPL_F1,ULTRACEMCO_F1,SBIN_F1,IOC_F1,ADANIPORTS_F1,SBILIFE_F1,JSWSTEEL_F1,BAJFINANCE_F1,CIPLA_F1,TATASTEEL_F1,HCLTECH_F1,DRREDDY_F1,TECHM_F1,NTPC_F1,INFY_F1,COALINDIA_F1,NESTLEIND_F1,SHREECEM_F1,TCS_F1,HDFCLIFE_F1,HINDUNILVR_F1,WIPRO_F1,BAJAJFINSV_F1,BPCL_F1,HDFC_F1,TATAMOTORS_F1,ONGC_F1,RELIANCE_F1,MARUTI_F1,POWERGRID_F1,AXISBANK_F1,TATACONSUM_F1,EICHERMOT_F1,M&M_F1,BAJAJ-AUTO_F1,DIVISLAB_F1,ITC_F1,TITAN_F1,HEROMOTOCO_F1,BRITANNIA_F1,HDFCBANK_F1,KOTAKBANK_F1,ICICIBANK_F1,BHARTIARTL_F1,INDUSINDBK_F1,SUNPHARMA_F1"

	# NIFTY100
	#SYMBOL="ACC_F1"
	SYMBOL="VEDL_F1,APOLLOHOSP_F1,RELIANCE_F1,TORNTPHARM_F1,ADANITRANS_F1,PIIND_F1,DIVISLAB_F1,PEL_F1,INDUSTOWER_F1,BANDHANBNK_F1,LTI_F1,ITC_F1,INFY_F1,AUROPHARMA_F1,HAVELLS_F1,TATACONSUM_F1,GAIL_F1,TECHM_F1,GRASIM_F1,YESBANK_F1,BIOCON_F1,DLF_F1,IGL_F1,TATAMOTORS_F1,ICICIGI_F1,ONGC_F1,CIPLA_F1,GODREJCP_F1,ADANIGREEN_F1,TITAN_F1,KOTAKBANK_F1,CADILAHC_F1,UPL_F1,BHARTIARTL_F1,BAJAJHLDNG_F1,ADANIENT_F1,POWERGRID_F1,GLAND_F1,MCDOWELL-N_F1,HCLTECH_F1,LUPIN_F1,NESTLEIND_F1,MARICO_F1,DABUR_F1,SBICARD_F1,ULTRACEMCO_F1,HDFCBANK_F1,SUNPHARMA_F1,HDFCLIFE_F1,NAUKRI_F1,TCS_F1,NMDC_F1,ADANIPORTS_F1,NTPC_F1,DRREDDY_F1,DMART_F1,HDFCAMC_F1,WIPRO_F1,PGHH_F1,JUBLFOOD_F1,ICICIPRULI_F1,M&M_F1,PIDILITIND_F1,BANKBARODA_F1,COALINDIA_F1,SBIN_F1,JINDALSTEL_F1,BAJAJFINSV_F1,SBILIFE_F1,BAJAJ-AUTO_F1,TATASTEEL_F1,HDFC_F1,EICHERMOT_F1,ASIANPAINT_F1,BAJFINANCE_F1,SAIL_F1,BPCL_F1,JSWSTEEL_F1,LT_F1,BERGEPAINT_F1,MUTHOOTFIN_F1,AXISBANK_F1,COLPAL_F1,HEROMOTOCO_F1,AMBUJACEM_F1,SHREECEM_F1,CHOLAFIN_F1,HINDALCO_F1,PNB_F1,ICICIBANK_F1,BOSCHLTD_F1,ACC_F1,HINDUNILVR_F1,IOC_F1,INDUSINDBK_F1,BRITANNIA_F1,MARUTI_F1,HINDPETRO_F1,INDIGO_F1,SIEMENS_F1"
	#SYMBOL="VEDL_EQ,APOLLOHOSP_EQ,RELIANCE_EQ,TORNTPHARM_EQ,ADANITRANS_EQ,PIIND_EQ,DIVISLAB_EQ,PEL_EQ,INDUSTOWER_EQ,BANDHANBNK_EQ,LTI_EQ,ITC_EQ,INFY_EQ,AUROPHARMA_EQ,HAVELLS_EQ,TATACONSUM_EQ,GAIL_EQ,TECHM_EQ,GRASIM_EQ,YESBANK_EQ,BIOCON_EQ,DLF_EQ,IGL_EQ,TATAMOTORS_EQ,ICICIGI_EQ,ONGC_EQ,CIPLA_EQ,GODREJCP_EQ,ADANIGREEN_EQ,TITAN_EQ,KOTAKBANK_EQ,CADILAHC_EQ,UPL_EQ,BHARTIARTL_EQ,BAJAJHLDNG_EQ,ADANIENT_EQ,POWERGRID_EQ,GLAND_EQ,MCDOWELL-N_EQ,HCLTECH_EQ,LUPIN_EQ,NESTLEIND_EQ,MARICO_EQ,DABUR_EQ,SBICARD_EQ,ULTRACEMCO_EQ,HDFCBANK_EQ,SUNPHARMA_EQ,HDFCLIFE_EQ,NAUKRI_EQ,TCS_EQ,NMDC_EQ,ADANIPORTS_EQ,NTPC_EQ,DRREDDY_EQ,DMART_EQ,HDFCAMC_EQ,WIPRO_EQ,PGHH_EQ,JUBLFOOD_EQ,ICICIPRULI_EQ,M&M_EQ,PIDILITIND_EQ,BANKBARODA_EQ,COALINDIA_EQ,SBIN_EQ,JINDALSTEL_EQ,BAJAJFINSV_EQ,SBILIFE_EQ,BAJAJ-AUTO_EQ,TATASTEEL_EQ,HDFC_EQ,EICHERMOT_EQ,ASIANPAINT_EQ,BAJFINANCE_EQ,SAIL_EQ,BPCL_EQ,JSWSTEEL_EQ,LT_EQ,BERGEPAINT_EQ,MUTHOOTFIN_EQ,AXISBANK_EQ,COLPAL_EQ,HEROMOTOCO_EQ,AMBUJACEM_EQ,SHREECEM_EQ,CHOLAFIN_EQ,HINDALCO_EQ,PNB_EQ,ICICIBANK_EQ,BOSCHLTD_EQ,ACC_EQ,HINDUNILVR_EQ,IOC_EQ,INDUSINDBK_EQ,BRITANNIA_EQ,MARUTI_EQ,HINDPETRO_EQ,INDIGO_EQ,SIEMENS_EQ"

	MODEWANTED=1
	ISOPTIONS=0

	configFile = open(configFilePath, "w")
	
	configFile.write("DATA="+Datafreq+"\nDATE="+Date+"\nMATCHINGRULE="+str(MATCHINGRULE)
	+"\nSLIPPAGE="+str(SLIPPAGE)+"\nSYMBOL="+SYMBOL+"\nDATATYPE="+DataType+"\nMODEWANTED="
	+str(MODEWANTED)+"\nISOPTIONS="+str(ISOPTIONS)+"\nMATCHINGBAR="+str(MATCHINGBAR)+
	#"\nMAXINPUTDATALENGTHFORINDICATORS="+MAXINPUTDATALENGTHFORINDICATORS+"\nEXECUTIONTIME="
	#+EXECUTIONTIME+"\nMAXINDICATORPASTVALUES="+MAXINDICATORPASTVALUES+"\nSLTRADE="+SLTRADE+
	#"\nSLSYMBOL="+SLSYMBOL+"\nSLTOTAL="+SLTOTAL+"\nTRAILINGSL="+TRAILINGSL+"\nBOOKPROFIT="+
	#BOOKPROFIT+"\nORDERVALUE="+ORDERVALUE+"\nGAPBETWEENORDERS="+GAPBETWEENORDERS+"\nMAXPYRAMIDSIZE="
	#+MAXPYRAMIDSIZE)
	"\nCHECKSIGNALWHENSLORDERISPENDING="+str(CHECKSIGNALWHENSLORDERISPENDING)+"\nINTERDAYSON="+str(INTERDAYSON)
	+"\nVOLUMEBASEDMACTHING="+str(VOLUMEBASEDMACTHING)+"\nPERCENTAGEVOLUMEMATCHING="+str(PERCENTAGEVOLUMEMATCHING)+
	"\nORDERMATCHINGINMULTBARS="+str(ORDERMATCHINGINMULTBARS))
	
	configFile.close()
	subprocess.call(['./simulator.out','indicatorsConfig.txt','config.txt','./'],cwd="../Strategy/Strategy"+str(StrategyNumber))

def main():
	
	StrategyNumber = sys.argv[1] 			# path to the directory

    # Datafreq = str(input())
	# DataType = str(input())
	# StartDate = str(input())
	# EndDate = str(input())

	Datafreq = sys.argv[2]
	DataType = sys.argv[3]
	StartDate = sys.argv[4]
	EndDate = sys.argv[5]
	MATCHINGBAR=sys.argv[6]
	MAXINPUTDATALENGTHFORINDICATORS=sys.argv[7]
	EXECUTIONTIME=sys.argv[8]
	MAXINDICATORPASTVALUES=sys.argv[9]
	SLTRADE=sys.argv[10]
	SLSYMBOL=sys.argv[11]
	SLTOTAL=sys.argv[12]
	TRAILINGSL=sys.argv[13]
	BOOKPROFIT=sys.argv[14]
	ORDERVALUE=sys.argv[15]
	GAPBETWEENORDERS=sys.argv[16]
	MAXPYRAMIDSIZE=sys.argv[17]
	CHECKSIGNALWHENSLORDERISPENDING=sys.argv[18]
	INTERDAYSON=sys.argv[19]
	VOLUMEBASEDMACTHING=sys.argv[20]
	PERCENTAGEVOLUMEMATCHING=sys.argv[21]
	ORDERMATCHINGINMULTBARS=sys.argv[22]

	StartYYYY = int(StartDate[:4])
	EndYYYY = int(EndDate[:4])
	StartMMDD = StartDate[4:8]
	EndMMDD = EndDate[4:8]

	for year in range(StartYYYY, EndYYYY+1):
		DataFileDirectory = "/home/data/nsedata/" + Datafreq + "/" + "CM" + "/" + str(year)
		if year == StartYYYY and year == EndYYYY:
			fileList = []
			for f in listdir(DataFileDirectory):
                            fileList.append(f[7:11])
			fileList.sort()
			for f in fileList:
				if f >= StartMMDD and f<=EndMMDD:
					changeConfig(StrategyNumber,Datafreq ,str(year) + f , DataType,MATCHINGBAR,MAXINPUTDATALENGTHFORINDICATORS,EXECUTIONTIME,MAXINDICATORPASTVALUES,SLTRADE,SLSYMBOL,SLTOTAL,TRAILINGSL,BOOKPROFIT,ORDERVALUE,GAPBETWEENORDERS,MAXPYRAMIDSIZE,CHECKSIGNALWHENSLORDERISPENDING,INTERDAYSON,VOLUMEBASEDMACTHING,PERCENTAGEVOLUMEMATCHING,ORDERMATCHINGINMULTBARS)
		elif year == StartYYYY:
			fileList = []
			for f in listdir(DataFileDirectory):
                            fileList.append(f[7:11])
			fileList.sort()
			for f in fileList:	
				if f >= StartMMDD:
					changeConfig(StrategyNumber,Datafreq ,str(year) + f , DataType,MATCHINGBAR,MAXINPUTDATALENGTHFORINDICATORS,EXECUTIONTIME,MAXINDICATORPASTVALUES,SLTRADE,SLSYMBOL,SLTOTAL,TRAILINGSL,BOOKPROFIT,ORDERVALUE,GAPBETWEENORDERS,MAXPYRAMIDSIZE,CHECKSIGNALWHENSLORDERISPENDING,INTERDAYSON,VOLUMEBASEDMACTHING,PERCENTAGEVOLUMEMATCHING,ORDERMATCHINGINMULTBARS)
		elif year == EndYYYY:
			fileList = []
			for f in listdir(DataFileDirectory):
                            fileList.append(f[7:11])
			fileList.sort()
			for f in fileList:	
				if f<= EndMMDD:
					changeConfig(StrategyNumber,Datafreq ,str(year) + f , DataType,MATCHINGBAR,MAXINPUTDATALENGTHFORINDICATORS,EXECUTIONTIME,MAXINDICATORPASTVALUES,SLTRADE,SLSYMBOL,SLTOTAL,TRAILINGSL,BOOKPROFIT,ORDERVALUE,GAPBETWEENORDERS,MAXPYRAMIDSIZE,CHECKSIGNALWHENSLORDERISPENDING,INTERDAYSON,VOLUMEBASEDMACTHING,PERCENTAGEVOLUMEMATCHING,ORDERMATCHINGINMULTBARS)
		else:
			fileList = []
			for f in listdir(DataFileDirectory):
                            fileList.append(f[7:11])
			fileList.sort()
			for f in fileList:
				changeConfig(StrategyNumber,Datafreq ,str(year) + f , DataType,MATCHINGBAR,MAXINPUTDATALENGTHFORINDICATORS,EXECUTIONTIME,MAXINDICATORPASTVALUES,SLTRADE,SLSYMBOL,SLTOTAL,TRAILINGSL,BOOKPROFIT,ORDERVALUE,GAPBETWEENORDERS,MAXPYRAMIDSIZE,CHECKSIGNALWHENSLORDERISPENDING,INTERDAYSON,VOLUMEBASEDMACTHING,PERCENTAGEVOLUMEMATCHING,ORDERMATCHINGINMULTBARS)


if __name__=="__main__":
    main()
